

# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {reg_num[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_num[0]}]
set_property PACKAGE_PIN V16 [get_ports {reg_num[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_num[1]}]
set_property PACKAGE_PIN W16 [get_ports {reg_num[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_num[2]}]
set_property PACKAGE_PIN W17 [get_ports {reg_num[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_num[3]}]
set_property PACKAGE_PIN W15 [get_ports {reg_num[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {reg_num[4]}]
set_property PACKAGE_PIN R2 [get_ports {pc_reset}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {pc_reset}]
 

# LEDs
set_property PACKAGE_PIN U16 [get_ports {out[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property PACKAGE_PIN E19 [get_ports {out[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property PACKAGE_PIN U19 [get_ports {out[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property PACKAGE_PIN V19 [get_ports {out[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property PACKAGE_PIN W18 [get_ports {out[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property PACKAGE_PIN U15 [get_ports {out[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property PACKAGE_PIN U14 [get_ports {out[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property PACKAGE_PIN V14 [get_ports {out[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
set_property PACKAGE_PIN V13 [get_ports {ACC[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ACC[0]}]
set_property PACKAGE_PIN V3 [get_ports {ACC[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ACC[1]}]
set_property PACKAGE_PIN W3 [get_ports {ACC[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ACC[2]}]
set_property PACKAGE_PIN U3 [get_ports {ACC[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ACC[3]}]
set_property PACKAGE_PIN P3 [get_ports {ACC[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ACC[4]}]
set_property PACKAGE_PIN N3 [get_ports {ACC[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ACC[5]}]
set_property PACKAGE_PIN P1 [get_ports {ACC[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ACC[6]}]
set_property PACKAGE_PIN L1 [get_ports {ACC[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {ACC[7]}]
	
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {pc_disp[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {pc_disp[0]}]
set_property PACKAGE_PIN W6 [get_ports {pc_disp[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {pc_disp[1]}]
set_property PACKAGE_PIN U8 [get_ports {pc_disp[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {pc_disp[2]}]
set_property PACKAGE_PIN V8 [get_ports {pc_disp[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {pc_disp[3]}]
set_property PACKAGE_PIN U5 [get_ports {pc_disp[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {pc_disp[4]}]
set_property PACKAGE_PIN V5 [get_ports {pc_disp[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {pc_disp[5]}]
set_property PACKAGE_PIN U7 [get_ports {pc_disp[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {pc_disp[6]}]
